#! /bin/bash

# TODO: do we also ant reads? 

set -e

if [ $# != 1 ]; then
    echo "Usage: $0 <ZNS device (e.g., nvme0n2)>"
    exit 1
fi

DEV=$(echo $1 | sed 's/vme/g/g')
DEV_SECT_SIZE=$(cat /sys/block/$1/queue/hw_sector_size)
DEV_ZONE_SIZE_BLOCKS=$(cat /sys/block/$1/queue/chunk_sectors)
DEV_ZONE_SIZE=$(echo "${DEV_ZONE_SIZE_BLOCKS} * 512" | bc)
DEV_ZONES=$(cat /sys/block/$1/queue/nr_zones)

mkdir -p data

##################################
## fio options for specific ZNS ##
##################################
BS=$(echo "${DEV_SECT_SIZE} * ${DEV_ZONE_SIZE}" | bc)
# 4 zone for writes, as lowest reset rate is 50% = 1 write for every 1 reset 
# issued which for 1000 zones is only 64K * 1023 = ~64MiB written (64K below). 
# This is the smalles zone size we will have, so we do not need a lot of space 
# for concurrent writing.
CONCUR_FILL=4 # concurrent fill jobs to speedup filling
WRITE_SIZE=${CONCUR_FILL} 
FILL_SIZE=$(echo "${DEV_ZONES} - ${WRITE_SIZE}" | bc) # All but the write zones
CONCUR_FILL_SIZE=$(echo "scale=0; ${DEV_ZONES} / ${CONCUR_FILL} - 1" | bc)

FILL_DIST=$(echo "${FILL_SIZE} * ${DEV_ZONE_SIZE} * ${DEV_SECT_SIZE}" | bc)
WRITE_DIST=$(echo "${WRITE_SIZE} * ${DEV_ZONE_SIZE} * ${DEV_SECT_SIZE}" | bc)

TRIM_IODEPTH=(1 2 4 8 16 32 64 128)
TRIM_FLOW=(100 99 95 90 75 50)

for trim_iodepth in ${TRIM_IODEPTH[@]}; do
    for trim_flow in ${TRIM_FLOW[@]}; do
        write_flow=$((100 - ${trim_flow}))
        echo "Benchmarking TRIM_IODEPTH ${trim_iodepth}: <TRIM_FLOW ${trim_flow} - WRITE_FLOW ${write_flow}>"
        sudo nvme zns reset-zone /dev/$1 -a

        # TODO: remove hardcoded paths
        if [[ ${write_flow} -eq 0 ]]; then
            # With 0 write flow we want to disable the concurrent write workload
            sudo env "DEV=${DEV}" "BS=${DEV_ZONE_SIZE}" "CONCUR_FILL_SIZE=${CONCUR_FILL_SIZE}" "CONCUR_FILL=${CONCUR_FILL}" "FILL_SIZE=${FILL_SIZE}" "TRIM_IODEPTH=${trim_iodepth}" "WRITE_SIZE=0" "FILL_DIST=${FILL_DIST}" "WRITE_DIST=0" "WRITE_FLOW=0" "TRIM_FLOW=${trim_flow}" /home/user/src/zns-contracts/fio/fio --output-format=json --output=data/data-trim_iod_${trim_iodepth}-tflow_${trim_flow}.json job.fio
        else
            sudo env "DEV=${DEV}" "BS=${DEV_ZONE_SIZE}" "CONCUR_FILL_SIZE=${CONCUR_FILL_SIZE}" "CONCUR_FILL=${CONCUR_FILL}" "FILL_SIZE=${FILL_SIZE}" "TRIM_IODEPTH=${trim_iodepth}" "WRITE_SIZE=${WRITE_SIZE}" "FILL_DIST=${FILL_DIST}" "WRITE_DIST=${WRITE_DIST}" "WRITE_FLOW=${write_flow}" "TRIM_FLOW=${trim_flow}" /home/user/src/zns-contracts/fio/fio --output-format=json --output=data/data-trim_iod_${trim_iodepth}-tflow_${trim_flow}.json job.fio
        fi
    done
done
